nodejs:
  replicaCount: 1
  nameOverride: dev-core-api-v2
  imagePullSecrets:
    name: wfregistry
  image:
    repository: 414928843086.dkr.ecr.ap-southeast-1.amazonaws.com/core-api-v2
    pullPolicy: Always
  containerPorts:
    - 3000
  env:
    - name: NODE_ENV
      value: development
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: 3000
    - name: LOGGER_LEVEL
      value: "error,log,warn,debug,verbose"
    - name: DB_DIALECT
      valueFrom:
        secretKeyRef:
          key: DB_DIALECT
          name: core-api
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          key: DB_PORT
          name: core-api
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          key: DB_HOST
          name: core-api
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: DB_USERNAME
          name: core-api
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: DB_PASSWORD
          name: core-api
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          key: DB_NAME
          name: core-api
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          key: JWT_SECRET
          name: core-api
    - name: JWT_EXPIRATION
      valueFrom:
        secretKeyRef:
          key: JWT_EXPIRATION
          name: core-api
  workingDir: /var/source
  resources:
    limits:
      cpu: 600m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 300Mi
  healthCheck:
    httpGet:
      path: /health
      port: 3000
  type: ClusterIP
  default:
    ports:
      - name: dev-core-api-v2-http
        externalPort: 80
        internalPort: 3000
        protocol: TCP
